---
title: Ciencia Abierta
subtitle: La intersección entre Ciencia y Código Libre
author: Jesús M. Castagnetto, Ph.D.
job: Universidad Peruana Cayetano Heredia
#biglogo: upch-logo-2013.png
logo: upch-logo.png
license: by-nc-sa
framework: io2012
widgets : [mathjax]
mode : selfcontained # {standalone, selfcontained, draft}

---

## Agenda

> - La Ciencia, su metodología y filosofía
> - Ciencia y Código Libre/Abierto
> - Tendencias
> 	- Acceso Abierto (*Open Access*)
>  	- Ciencia Abierta (*Open Science*)
>  	- Investigación Reproducible (*Reproducible Research*)

---

## Ciencia - Definición

<q>
La actividad intelectual y práctica que involucra el estudio sistemático de
la estructura y comportamiento del universo, a través de la observación
y experimentación.
</q>

<div class="footer">Scientia (latin): Conocimiento</div>

--- 

## Método científico

> 1. Observación objetiva (mediciones y datos)
> 2. Formulación del problema (considerar la evidencia)
> 3. Generación de Hipótesis (explicar lo observado)
> 4. Derivación de Predicciones cuantificables
> 5. Experimentación/Prueba (basado en la predicción)
> 6. Análisis de los resultados (escrutinio y valoración)

---

<q>La Ciencia no nos da la verdad absoluta, la ciencia es un mecanismo. Es un
modo de mejorar nuestro conocimiento de la naturaleza, un sistema para
contrastar nuestros pensamientos con el universo y ver si coinciden.
<div class="author">Isaac Asimoc</div>
</q>

---

## Hipótesis científica

- Provee una explicación de los fenómenos observados, la cual tiene que se
  comprobada fehacientemente.
- Idealmente tiene que:
    - Poder explicar fenómenos futuros (poder predictivo)
	- Evitar la complejidad excesiva y sin razón ("_Navaja de Occam_")
	- Ser cuantificable y comprobable
	- Tener un alcance definido

--- 

## El cuento de la oveja negra

Tres amigos estaban viajando en un tren: un abogado, un físico y un matemático.

> - El abogado vió por la ventana y dijo: "Las ovejas de esta región son negras"
> - El físico dijo: "No, eso es incorrecto: _algunas_ ovejas de esta región son negras"
> - El matemático, algo molesto dijo: "Hay al menos un campo en esta región, conteniendo al menos una oveja, la cual tiene al menos un lado de color negro"

---

## Teoría científica

- Una explicación comprobada de algún aspecto de la naturaleza.
- La comprobación debe haber sido repetida y repetible en forma independiente,
  a través de la observación y la experimentación.
- Puede hacer predicciones que pueden ser probadas falsas
  (_falsificable_/_falseable_)
- Es consistente con teorías científicas pre-existentes.

---

## Falseabilidad en Ciencia

> - Un concepto central: _la inherente posibilidad de comprobar
>   (experimentalmente) que una afirmación (hipótesis o teoría) acerca del
>   comportamiento de la naturaleza, resulta ser **falsa**_ 
> - En su forma menos dura: "*la afirmación resulta ser incompleta*"
> - Esto implica que los científicos tienen que estar dispuestos a aceptar
>   teorías nuevas que expliquen mejor lo observado

---

<q>Toda la Ciencia es incierta y sujeta a revisión. Lo glorioso de la ciencia
es el (*poder*) imaginar mas de lo que podemos probar.
<div class="author">Freeman Dyson</div>
</q>

--- .segue

## Ciencia \(\iff\) Código Libre

---

## El quehacer científico

- El trabajo en Ciencia es inherentemente colaborativo
- Implica compartir libremente lo aprendido
- Uso de un lenguaje común, concreto y preciso
- Experiencia resumida en un conjunto de teorías
- Muchas comunidades pero los mismos objetivos
- Se fundamenta en la meritocracia

---

## Discusión abierta

- Revisión crítica de resultados, hipótesis y teorías
- Revisión de (tus) publicaciones por (tus) pares
- Mecanismos para la retracción de publicaciones
- Objetividad y pragmatismo como presupuestos

---

## Mejoras continuas

- Los avances se basan en conocimiento pre-existente
- Refinamiento de hipótesis y teorías, frente a nuevos resultados
- Avances (y retrocesos) en investigación interdisciplinaria
- Ocasionalmente, cambios paradigmáticos

---

<q>La Ciencia es una forma de pensar mucho mas que ser un conjunto de
conocimientos acumulados.
<div class="author">Carl Sagan</div>
</q>

--- .segue

## Acceso Abierto (Open Access)

---

## Inicios de Acceso Abierto

- Budapest Open Access Initiative (2002)
   - http://www.budapestopenaccessinitiative.org/read
- Bethesda Statement on Open Access Publishing (2003)
   - http://dash.harvard.edu/handle/1/4725199
- Berlin Declaration on Open Access to Knowledge in the Sciences and Humanities
  (2003)
   - http://openaccess.mpg.de/286432/Berlin-Declaration

---

## Definición de Acceso Abierto

<q>\(\ldots\)Por 'acceso abierto'\(\ldots\)queremos decir su disponibilidad
gratuita en Internet público, permitiendo a cualquier usuario leer, descargar,
copiar, distribuir, imprimir, buscar o usarlos con cualquier propósito legal,
sin ninguna barrera financiera, legal o técnica\(\ldots\)
<div class="author">Definición de Budapest (2002)</div>
</q>

---

## Copyright en Acceso Abierto

<q>\(\ldots\)La única limitación en cuanto a reproducción y distribución  y el
único rol del copyright en este dominio, deberá ser dar a los autores el
control sobre la integridad de sus trabajos y el derecho de ser adecuadamente
reconocidos y citados\(\ldots\)
<div class="author">Definición de Budapest (2002)</div>
</q>

---

## Acceso Abierto

- Acceso en línea, libre, inmediato y permamente a toda la información
  científica y técnica que se publica.
- Incluye: artículos en revistas, libros, bases de datos, etc.
- Favorece a todos: Autores, Instituciones y al Público en General
- Un movimiento que comenzó hace una década (~2003)
- Ha pasado a ser el modo aceptable y aceptado de publicar

---

## Publicando en Acceso Abierto

- Políticas de publicación abierta por parte de entidades financiadoras,
  universidades, etc. (ej: http://publicaccess.nih.gov/)
- Muchas compañías editoras tienen ahora posibilidad de publicar en Acceso
  Abierto
- Recursos:
    - Reg. of Open Access Rep. (ROAR): http://roar.eprints.org/
	- ROARMAP (Mandates): http://roarmap.eprints.org/
	- DOAJ: http://www.doaj.org/

--- 

## La importancia de Acceso Abierto

<q>Open Knowledge [saves
lives](http://blogs.ch.cam.ac.uk/pmr/2011/10/24/open-access-saves-lives/) 
\(\ldots\)<br/>
Closed access means people die
<div class="author">[Peter
Murray-Rust](http://blogs.ch.cam.ac.uk/pmr/2011/10/23/open-research-reports-what-jenny-and-i-said-and-why-i-am-angry/)</div></q>


--- .segue

## Ciencia Abierta (Open Science)

---

## ¿Que es "Ciencia Abierta"?

- Un término general que incluye
    - Publicar en Acceso Abierto
	- Conducir investigación en forma abierta al estilo de los proyectos de
	  Código Libre/Abierto (**Open Research**)
    - Mantener los registros primarios
	  de la investigación en forma pública (**Open Notebook Science**)




--- .segue

## Investigación Reproducible<br/><br/>(Reproducible Research)

---

- http://biostat.mc.vanderbilt.edu/wiki/Main/StatReport
- http://cran.r-project.org/web/views/ReproducibleResearch.html
- http://www.opensciencedirectory.net/
- https://openscienceframework.org/
- http://www.openscience.org/blog/

---

<q>One thing I have learned in a long life: that all our science, measured
against reality, is primitive and childlike — and yet it is the most precious
thing we have.
<div class="author">Albert Einstein</div>
</q>

--- .thank-you-slide .segue

## ¡Muchas Gracias!

Jesús M. Castagnetto (jesus@upch.pe)
